export const Routes = {
  home: "home",
  auth: {
    navigator: "auth",
    login: "auth/login",
    otp: "auth/otp",
    forgot_password_otp: "auth/forgot_password_otp",
    forgot_password_create_new: "auth/forgot_password_create_new",
    create_account: "auth/create_account",
    forgot_password: "auth/forgot_password",
    reset_password: "auth/reset_password",
    kyc: "auth/kyc",
    document_photo: "auth/document_photo",
    plans: "auth/plans",
    start_trading: "auth/start_trading",
  },
  main: {
    navigator: "main",
    home: "main/home",
    transactionHistory: "main/transactionHistory",
    referrals: {
      navigator: "main/referrals",
      information: "main/referrals/information",
      levelDetails: "main/referrals/level_details",
    },
    profile: {
      navigator: "main/profile",
      userProfile: "main/profile/user_profile",
      support: "main/profile/support",
      changePassword: "main/profile/change_password",
      logout: "main/profile/logout",
    },
    wallet: {
      navigator: "main/wallet",
      walletDetails: "main/wallet/detail",
      deposit: "main/wallet/deposit",
      withdraw: "main/wallet/withdraw",
      historyPositionDetails: "main/wallet/position_details",
      qr_scanner: "main/wallet/qr_scanner",
    },
    invest: {
      navigator: "main/invest",
      walletDetails: "main/invest/detail",
      deposit: "main/invest/deposit",
      refund: "main/invest/refund",
      qr_scanner: "main/invest/qr_scanner",
    },
    trading: {
      navigator: "main/trading",
      tradingDetails: "main/trading/detail",
    },
  },
  notFound: "notFound",
} as const
